name: lively
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 
  json_annotation:  
  flutter_bloc:
  firebase_core: 
  firebase_auth: 
  cloud_firestore:
  l:
<<<<<<< HEAD
  cupertino_icons:
  lottie: 
  dio: ^4.0.4

=======
  cupertino_icons: ^1.0.2
>>>>>>> f5e6049 (Home screen top buttons and text UI)

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner: 
  json_serializable:  
  dart_code_metrics:
  flutter_lints: 

flutter:
<<<<<<< HEAD
  assets:
  - assets/
=======
>>>>>>> f5e6049 (Home screen top buttons and text UI)
  uses-material-design: true
  fonts:
    - family: AppIcons
      fonts:
<<<<<<< HEAD
        - asset: assets/fonts/LivelyIcons.ttf
=======
>>>>>>> f5e6049 (Home screen top buttons and text UI)
        - asset: assets/fonts/AppIcons.ttf

flutter_intl:
  enabled: true
