name: lively
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: 
  json_annotation:  
  flutter_bloc:
  firebase_core: 
  firebase_auth: 
  cloud_firestore:
  l:
  cupertino_icons:
  lottie: 
  dio: ^4.0.4
  just_audio: 
  cloud_functions: ^3.2.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  build_runner: 
  json_serializable:  
  dart_code_metrics:


flutter:
  assets:
  - assets/animations_lottie/
  uses-material-design: true
  fonts:
    - family: LivelyIcons
      fonts:
        - asset: assets/fonts/LivelyIcons.ttf
    - family: Muller
      fonts:
        - asset: assets/fonts/Muller-Trial-ExtraBold.ttf
        - asset: assets/fonts/Muller-Trial-Regular.ttf

flutter_intl:
  enabled: true
