name: lively
description: lively-radio.

publish_to: 'none'
version: 1.0.2+5

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
    
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  web_socket_channel: ^2.4.0
  just_audio: ^0.9.27
  audio_service: ^0.18.6
  url_launcher: ^6.1.4
  introduction_screen: ^3.0.2

  
  video_player: ^2.8.2


  flutter_map: ^4.0.0
  geolocator: ^10.1.0
  flutter_map_marker_cluster: ^1.1.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.2.0
  device_info_plus: ^9.1.2
  supabase: ^2.0.4
  marquee_widget: ^1.2.0
  flutter_local_notifications: ^16.3.0
  flutter_svg: ^2.0.9
  flutter_background_service: ^5.0.5
  appmetrica_plugin: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:  ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  build_runner: ^2.1.11
  json_serializable:  ^6.2.0 
  dart_code_metrics: ^5.7.6
  l: ^4.0.2
  flutter_native_splash: ^2.2.4
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  image_path: assets/ic_launcher.png
  adaptive_icon_background: "#F64B4B"
  adaptive_icon_foreground: assets/ic_launcher_foreground.png
  ios: false
  
  

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#363636"
  image: assets/splash.png
  image_dark: assets/splash-dark.png
  
  android 12:
    color: "#FFFFFF"
    color_dark: "#363636"
    image: assets/splash.png
    image_dark: assets/splash-dark.png
  ios: true

flutter:
  assets: 
    - assets/firstStartVideo.mp4
    - assets/map_icon.png
    - assets/map_icon.svg
    - assets/marker_map.png
    - assets/marker_map.svg
    - assets/marker_map_count.png
    - assets/close_map.png
    - assets/close_map.svg
    
  uses-material-design: true
  fonts:
    - family: LivelyIcons
      fonts:
        - asset: assets/fonts/LivelyIcons.ttf
    - family: Muller
      fonts:
        - asset: assets/fonts/MullerExtraBold.ttf
        - asset: assets/fonts/MullerRegular.ttf

flutter_intl:
  enabled: true
