name: lively
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  firebase_core: ^1.19.1
  firebase_crashlytics: ^2.8.4
  cloud_firestore: ^3.2.1
  web_socket_channel: ^2.2.0
  just_audio: ^0.9.27
  audio_service: ^0.18.6
   
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:  ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  build_runner: ^2.1.11
  json_serializable:  ^6.2.0 
  dart_code_metrics: ^4.16.0
  l: ^3.2.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"


flutter:
  assets: 
    - assets/
  uses-material-design: true
  fonts:
    - family: LivelyIcons
      fonts:
        - asset: assets/fonts/LivelyIcons.ttf
    - family: Muller
      fonts:
        - asset: assets/fonts/MullerExtraBold.ttf
        - asset: assets/fonts/Muller-Trial-Regular.ttf

flutter_intl:
  enabled: true
